compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmPublishRegistry: 'http://npm.cicd.contaazul.local/'

npmRegistries:
  //npm.cicd.contaazul.local:
    npmAlwaysAuth: false

npmRegistryServer: 'https://registry.npmjs.org/'

npmScopes:
  ca-tools-front:
    npmPublishRegistry: 'http://npm.cicd.contaazul.local/'
    npmRegistryServer: 'http://npm.cicd.contaazul.local/'
    npmAuthToken: ${NPM_TOKEN}
  contaazul:
    npmPublishRegistry: 'http://npm.cicd.contaazul.local/'
    npmRegistryServer: 'http://npm.cicd.contaazul.local/'
    npmAuthToken: ${NPM_TOKEN}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/ContaAzul/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

unsafeHttpWhitelist:
  - '*.contaazul.local'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
